version: '3.9'

services:
  web:
    user: root
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./backend/:/app/
      - static_volume:/static/
      - media_volume:/media/
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  db-dev:
    image: postgres:15.1-alpine
    restart: always
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
  static_volume:
  media_volume: